### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by artemsolod** [JunoLab/FuzzyCompletions.jl#2]
Thanks for this great package! I was wandering if the experience could be improved by making ranking case sensitive. Right now the first suggestion for `nthng` (and `nothing`) is `Nothing` which is probably not ideal. I looked at fuzzy-completion in RStudio and it seems to take into account capitalization. Are there some considerations for the current behaviour? 

(tested within Juno 0.8.2, Atom 0.12.11)

**Comment by aviatesk** [comment]
your suggestions sounds really good, well I'm not sure we can spend much time in this package in the near future.
as a pointer in a case if you want to hack on this package by yourself, we are currently just using `REPL.fuzzyscore` for our scoring logic ([here](https://github.com/JunoLab/FuzzyCompletions.jl/blob/master/src/FuzzyCompletions.jl#L12) is the code), so you can tweak this function to introduce case sensitivity.
I will be glad to take a look at a PR if you can.
