### ISSUE TITLE
Autocomplete nested Dicts

### ISSUE THREAD

**Issue by disberd** [JunoLab/FuzzyCompletions.jl#9]
I noticed that first level keys of Dictionaries are nicely handled by FuzzyCompletions but when trying to autocomplete keys at higher levels of nested dicts the autocompletion doesn't work anymore.

I have noticed that nested autocompletion is also an issue with standard REPL completions so it might be a design decision, but would it be feasible to have nested dict completion functionality?

**Comment by aviatesk** [comment]
I think it's by design, since to access an inner dictionary, we first evaluate `getindex(::AbstractDict, key)` and it's just a generic function and involves arbitrary sub effects, and thus not might be safe to be called within completion pipeline.

**Comment by disberd** [comment]
Ok thanks for the clarification, I suppose this issue might be closed then

**Comment by pfitzseb** [comment]
Technically evaluating `propertynames` could have side-effects as well :P But yes, I agree with the reasoning.
